name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - uses: lowlighter/metrics@latest
        with:
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_playlist: https://6WGuHw3q1p7NnZAYj0I5zv
          plugin_music_limit: 4
      - uses: lowlighter/metrics@latest
        with:
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_mode: recent
          plugin_music_limit: 8
      - uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_languages_ignored: "" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip
      - uses: lowlighter/metrics@latest
        with:
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
      - uses: lowlighter/metrics@latest
        with:
          plugin_lines: yes
      - uses: lowlighter/metrics@latest
        with:
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Calcutta
      - uses: lowlighter/metrics@master
        with:
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14 # Max age for events, set to 0 for unlimited
